//Kth smallest element in a row-cpumn wise sorted matrix
//{ Driver Code Starts
// kth largest element in a 2d array sorted row-wise and column-wise
#include<bits/stdc++.h>
using namespace std;
#define MAX 1000
int mat[MAX][MAX];
int kthSmallest(int mat[MAX][MAX], int n, int k);
// driver program to test above function
int main()
{
    int t;
    cin>>t;
    while(t--)
    {
        int n;
        cin>>n;
    
        for(int i=0;i<n;i++)
            for(int j=0;j<n;j++)
                cin>>mat[i][j];
        int r;
        cin>>r;
        cout<<kthSmallest(mat,n,r)<<endl;
    }
     // cout << "7th smallest element is " << kthSmallest(mat, 4, 7);
      return 0;
}

// } Driver Code Ends



int kthSmallest(int mat[MAX][MAX], int n, int k)
{
  priority_queue<int>pq;
  int temp[n*n];
  int x=0;
  
   for(int i=0;i<n;i++)
   {
     for(int j=0;j<n;j++){
          temp[x]=mat[i][j];
          x++;
      }
   }
   
   for(int i=0;i<k;i++)
   {
       pq.push(temp[i]);
   }
 
      for(int i=k;i<x;i++)
      {
          if(temp[i]<pq.top())
          {
              pq.pop();
              pq.push(temp[i]);
          }
      }
      
      return pq.top();
}
